yarnPath: .yarn/releases/yarn-4.12.0.cjs
nodeLinker: node-modules
enableGlobalCache: true
packageExtensions:
  "@nuxt/devtools@*":
    peerDependencies:
      vue: "*"
  "@nuxt/eslint-config@*":
    peerDependencies:
      "@vue/compiler-sfc": "*"
      typescript: "*"
  "@nuxt/eslint-plugin@*":
    peerDependencies:
      typescript: "*"
  "@nuxt/eslint@*":
    peerDependencies:
      vite: "*"
  "nuxt@*":
    peerDependencies:
      "@vue/compiler-sfc": "*"
      vite: "*"
  "nuxt-site-config@*":
    peerDependencies:
      vue: "*"
  "nuxt-site-config-kit@*":
    peerDependencies:
      vue: "*"
