# File: .github/workflows/deployment.yml
# Name: Deployment
name: Build and Deployment
run-name: Building and Deploying by ${{ github.actor }}

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  HUSKY: 0

jobs:
  build_and_publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Build
        run: |
          yarn install --frozen-lockfile
          yarn build
          yarn generate

      # - name: Publish to Cloudflare Pages
      # uses: cloudflare/pages-action@v1
      # id: cloudflare
      # with:
      #   apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      #   accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      #   projectName: new-portfolio
      #   directory: dist
      #   gitHubToken: ${{ secrets.GITHUB_TOKEN }}
      #   branch: main
      #   wranglerVersion: "3"
      #
      - name: Deploy to Cloudflare
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist --project-name=new-portfolio
          wranglerVersion: "3"
        # Capture the deployment URL from the output
        env:
          DEPLOYMENT_URL: "https://<YOUR_PROJECT_NAME>.pages.dev"

      - name: Notify Build Status (Success)
        if: success()
        run: |
          BUILD_URL="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          DEPLOYMENT_URL="${{ env.DEPLOYMENT_URL }}"
          MESSAGE="✅ Deployment succeeded for commit ${GITHUB_SHA::6}.\n Access your site at: ${DEPLOYMENT_URL}.\n [View build](${BUILD_URL})"
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
            -d chat_id="${{ secrets.TELEGRAM_BOT_CHATROOM_ID }}" \
            -d text="$MESSAGE" || echo "Failed to send Telegram notification"

      - name: Notify Build Status (Failure)
        if: failure()
        run: |
          BUILD_URL="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          MESSAGE="❌ Deployment failed for commit ${GITHUB_SHA::6}.\n [View build](${BUILD_URL})"
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
            -d chat_id="${{ secrets.TELEGRAM_BOT_CHATROOM_ID }}" \
            -d text="$MESSAGE" || echo "Failed to send Telegram notification"
