# File: .github/workflows/deployment.yml
# Name: Deployment
name: Build and Deployment
run-name: Building and Deploying by ${{ github.actor }}

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  HUSKY: 0

jobs:
  build_and_publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Build
        run: |
          yarn install --frozen-lockfile
          yarn build
          yarn generate

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        id: cloudflare
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: new-portfolio
          directory: dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          wranglerVersion: "3"

      - name: Notify Build Status (Success)
        if: success()
        run: |
          BUILD_URL="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          MESSAGE="✅ Deployment succeeded for commit ${GITHUB_SHA::6}.\n Access your site at: ${{ steps.cloudflare.outputs.url }}.\n [View build](${BUILD_URL})"
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
            -d chat_id=${{ secrets.TELEGRAM_BOT_CHATROOM_ID }} \
            -d text="$MESSAGE"

      - name: Notify Build Status (Failure)
        if: failure()
        run: |
          BUILD_URL="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          MESSAGE="❌ Deployment failed for commit ${GITHUB_SHA::6}.\n [View build](${BUILD_URL})"
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
            -d chat_id=${{ secrets.TELEGRAM_BOT_CHATROOM_ID }} \
            -d text="$MESSAGE"
