# File: .github/workflows/deploy.yml
# Name: Deployment
name: Build and Deployment
run-name: Building and Deploying by ${{ github.actor }}

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint-check:
     name: Lint
     runs-on: ubuntu-latest
     permissions:
      contents: read
      packages: read
      # To report GitHub Actions status checks
      statuses: write

     steps:
        - name: Checkout code
          uses: actions/checkout@v4
          with:
            # super-linter needs the full git history to get the
            # list of files that changed across commits
            fetch-depth: 0

        - name: Super-linter
          uses: super-linter/super-linter/slim@v6.5.1  # x-release-please-version
          env:
            # To report GitHub Actions status checks
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ubuntu-latest
    needs: [lint-check]
    permissions:
      contents: read
      deployments: write

    name: Build and Publish
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Setup Node.js with the desired version
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20" # Specify the Node.js version here

      # Build step
      - name: Build
        run: |
          yarn install --frozen-lockfile
          yarn build
          yarn generate

      # Publish step
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: new-portfolio
          directory: dist
          # Optional: Enable this if you want to have GitHub Deployments triggered
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          # Optional: Switch what branch you are publishing to.
          # By default this will be the branch which triggered this workflow
          branch: main
          # Optional: Change the Wrangler version, allows you to point to a specific version or a tag such as `beta`
          wranglerVersion: "3"